### ISSUE TITLE
Error on build with React's JSX runtime.

### ISSUE THREAD

**Issue by jaymanmatthewsdev** [IniZio/iniz#161]
Hey, I am getting the current error in 0.2.0 when building for production.

![image](https://user-images.githubusercontent.com/108161206/195346602-13eef857-02dd-466b-b5ba-a3208a0079f8.png)

Worked fine in 0.1.*

**Comment by IniZio** [comment]
Hi @jaymanmatthewsdev what is the React version you are using?

**Comment by jaymanmatthewsdev** [comment]
> Hi @jaymanmatthewsdev what is the React version you are using?

I believe it was React 18.

**Comment by IniZio** [comment]
Released https://github.com/IniZio/iniz/releases/tag/%40iniz%2Freact%400.2.1

Closing this issue first, will reopen if can reproduce. Thanks for the report @jaymanmatthewsdev :)
